#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - gnupg
  - curl
  - net-tools

runcmd:
  # Set timezone
  - timedatectl set-timezone UTC

  # Install Graylog
  - wget https://packages.graylog2.org/repo/packages/graylog-6.0-repository_latest.deb
  - dpkg -i graylog-6.0-repository_latest.deb
  - apt-get update
  - apt-get install -y graylog-server
  - apt-mark hold graylog-server


  # Update or add required configurations (non-destructive)
  - sed -i '/^password_secret/c\password_secret = ${password_secret}' /etc/graylog/server/server.conf
  - sed -i '/^root_password_sha2/c\root_password_sha2 = ${root_password_sha2}' /etc/graylog/server/server.conf
  - sed -i '/^root_username/c\root_username = admin' /etc/graylog/server/server.conf
  - sed -i '/^#http_bind_address/c\http_bind_address = 0.0.0.0:9000' /etc/graylog/server/server.conf
  - sed -i '/^#elasticsearch_hosts/c\elasticsearch_hosts = http://${backend_ip}:9200' /etc/graylog/server/server.conf
  - sed -i '/^mongodb_uri/c\mongodb_uri = mongodb://${backend_ip}:27017/graylog' /etc/graylog/server/server.conf

    # Start Graylog
  - systemctl daemon-reload
  - systemctl enable graylog-server.service
  - systemctl start graylog-server.service

  # Output access info
  - |
    echo "Graylog installation complete!"
    echo "Web Interface: http://$(hostname -I | awk '{print $1}'):9000"
    echo "Username: admin"